### PR TITLE
Done with 2008 files

### PR DESCRIPTION
**Pull request by ssdatar**
Derek, please check if the files are okay. I've commented the code wherever possible.

### CODE REVIEW

**Comment by dwillis** [comment]
Looks pretty good, thanks! @ssdatar. Just a few things:

1. Can `2008/2008_0205__ga__primary__state__president.csv` be renamed to `2008/20080205__ga__primary__president.csv`?
2. You can drop the `_state` label from file names: we only need `_county` and `_precinct` where appropriate.
3. For special elections, can we say if it's a `special__general` or whatever?

Many thanks for this.

**Comment by ssdatar** [comment]
Is it okay if I manually rename them?

**Comment by dwillis** [comment]
Absolutely.

**Comment by ssdatar** [comment]
Renamed

**Comment by dwillis** [comment]
Thanks @ssdatar!

**Pull request merged**
